#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Default values for fluss.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  registry: ""
  repository: fluss
  tag: "0.9.0-incubating"
  pullPolicy: IfNotPresent
  pullSecrets: []

# Select certain nodes for Fluss pods.
nodeSelector: {}
affinity: {}
tolerations: []

# Add common labels to all objects and pods defined in this chart.
labels: {}

# Coordinator Server Config
coordinatorServer:
  # Number of coordinator servers in the deployment
  replicas: 1
  ## Configure extra options for coordinator server containers' liveness, readiness and startup probes
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes
  # If the coordinator server stops heartbeating for 6 minutes (100*3s),
  # kill the coordinator server and let Kubernetes restart it
  livenessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 3
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 100
  # If the coordinator server are temporarily unable to serve traffic for 6 minutes (100*3s),
  # mark not ready the coordinator server and don't send it requests
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 3
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 100

  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  persistence:
    enabled: false
    size: 1Gi
    storageClass:

# Tablet Server Config
tabletServer:
  # Number of tablet servers in the deployment
  replicas: 3
  ## Configure extra options for tablet server containers' liveness, readiness and startup probes
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes
  # If the tablet server stops heartbeating for 6 minutes (100*3s),
  # kill the tablet server and let Kubernetes restart it
  livenessProbe:
    failureThreshold: 100
    timeoutSeconds: 1
    initialDelaySeconds: 10
    periodSeconds: 3
  # If the coordinator server are temporarily unable to serve traffic for 6 minutes (100*3s),
  # mark not ready the coordinator server and don't send it requests
  readinessProbe:
    failureThreshold: 100
    timeoutSeconds: 1
    initialDelaySeconds: 10
    periodSeconds: 3

  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  persistence:
    enabled: false
    size: 10Gi
    storageClass:

# Service parameters
service:
  # @param service.ports.internal Fluss svc port for internal connections
  # @param service.ports.client Fluss svc port for client connections
  ports:
    internal: 9123
    client: 9124



# Fluss server configuration options
# Config settings to go into the mounted conf/server.yaml
# See more at https://fluss.apache.org/docs/maintenance/configuration/
configurationOverrides:
  default.bucket.number: 3
  default.replication.factor: 3
  zookeeper.path.root: /fluss
  zookeeper.address: zk-zookeeper.{{ .Release.Namespace }}.svc.cluster.local:2181
  remote.data.dir: /tmp/fluss/remote-data
  data.dir: /tmp/fluss/data
  internal.listener.name: INTERNAL
